/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.mid.readWriteDisplayTriangles;

import org.junit.Test;
import static org.junit.Assert.*;

public class RecordTest {
    @Test public void testRecordGetters() {
        Record classUnderTest = new Record();
        assertNotNull("Record should have a color", classUnderTest.getColor());
    }
}
